name: Chrome Extension CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v1
      - name: Install packages
        run: cd ./chrome-extension && yarn install
      - name: Run tests
        run: cd ./chrome-extension && yarn test:ci
